#!/usr/local/bin/bash

# get status

declare -A directories=(
	["Graphite"]="Value"
)

declare -a array=("es" "no")
refresh() {
	for VAR in ${!array}; do
		echo "$VAR"
	done
}

refresh
