#!/usr/local/bin/bash

# get status


declare -A directories=(
  "[Graphite]"="Value"
)

refresh() {
	STATUS=$(git status)
  echo ${directories["Graphite"]}
	# if [[ $STATUS != *" Changes not staged for commit: "* ]]; then
	# 	echo "Please add a commit message : "
	# 	read DETAILS
	# 	git add .
	# 	git commit -m "$DETAILS"
	# 	git push origin main
	# fi
}

refresh
